blank_issues_enabled: false
contact_links:
  - name: Star HPC Support
    url: https://docs.starhpc.hofstra.io/help/contact.html
    about: Contact Support if you're having trouble with your Star HPC account.
