name: Improve the content on docs.starhpc.hofstra.io
description: Make a suggestion or report a problem about the content of docs.starhpc.hofstra.io.
labels:
  - content
body:
  - type: markdown
    attributes:
      value: |
        * Before you file an issue read the [Contributing guide](https://docs.github.com/en/contributing).
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/StarHPC/docs/issues).

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to Star HPC's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true

  - type: textarea
    attributes:
      label: What articles on docs.starhpc.hofstra.io are affected?
      description: Please include links to related articles, pages you would like to be updated, screenshots, etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What changes would are you suggesting?
      description: |
        - Give as much detail as you can to help us understand the change you want to see. 
        - Why should the docs be changed? What use cases does it support? 
        - What is the expected outcome or behavior?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: |
        - Please provide any additional information, configuration, or data that might be necessary to reproduce the issue.
        - Are you able to reliably reproduce the problem? How often does it occur? How many users are affected?
        - Add any other context or screenshots about the feature here.
    validations:
      required: false
